### ISSUE TITLE
configure: error: could not make ./config.status

### ISSUE THREAD

**Issue by stdedos** [rocky/zshdb#27] opened 2020-06-21 17:28 UTC
Has anyone seen:

```console
$ ./autogen.sh
configure.ac:6: installing './install-sh'
configure.ac:6: installing './missing'
Running configure with --enable-maintainer-mode 
checking whether to enable maintainer-specific portions of Makefiles... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for grep that handles long lines and -e... /bin/grep
checking for a sed that does not truncate output... /bin/sed
checking for zsh... /usr/bin/zsh
checking Checking whether /usr/bin/zsh is compatible with zshdb... zsh 5.4.2 (x86_64-ubuntu-linux-gnu) is recent enough.
yes!
checking for diff... /usr/bin/diff
adding -w to diff in regression tests
adding --unified to diff in regression tests
checking whether ln -s works... yes
checking for rm... /bin/rm
checking that generated files are newer than configure... done
configure: creating ./config.status
configure: error: could not make ./config.status
$ echo $?
1
```

Internet does not help e.g. https://apple.stackexchange.com/questions/262670/build-fails-with-configure-error-could-not-make-config-status

Everyone is saying the issues being about "non-standard" tools, but I have no idea what _standard tools are_.

**Comment by rocky** [comment] 2020-06-21 20:33
If that link is you, it says the problem is solved. Howerver I think not since that is on an Apple forum and you seem to be running this from Ubuntu. 

>  but I have no idea what standard tools are.

I have no idea what non-standard tools (or more likely a somewhat unusual environment) you have. 


So let's just try to understand what the `configure` program is doing and what it is trying to tell you.

Configure runs a number of programs to look for features and programs that need to be around and where they are located in order to customize things that are customizable. 

For example when the program reports: 

> checking for grep that handles long lines and -e... /bin/grep
> checking for a sed that does not truncate output... /bin/sed
> checking for zsh... /usr/bin/zsh

the program has learned that you have a "grep" in at the location `/bin/grep` and it handles long lines. Also that you have a "sed" program that does not truncate output in `/bin/sed` and that your "zsh" is located in "/usr/bin/zsh" and at version 5.4.2 which recent enough to be used.

You get the idea.

So now we get to the error and message leading up to that:

> configure: creating ./config.status
>  configure: error: could not make ./config.status

After configure has accumulated the information above, it needs to store it somewhere, and that place it has chosen is `./config.status`.  When it tries to write out that file, it can't and that what the "could not make ./config.status" message says.

The most likely causes is that configure dow not have write access to "." or that there already is a file called "./config.status" that has permissions set in a way that you can't write to it. For example it could be owned by `root` (from a prior run) and you are now running this as some other non-priviledged user.

Since this is more of a "help" what am I doing wrong kind of question rather than a bug report, I'm closing this.

If you want helpdesk kind of support, then consider sponsoring either the project or me.

**Closed by rocky** 2020-06-21 20:33 UTC
Labels: help requested

**Comment by stdedos** [comment] 2020-06-21 21:15
Hello there, and thank you for the fullest of responses!

> If that link is you, it says the problem is solved. Howerver I think not since that is on an Apple forum and you seem to be running this from Ubuntu.

Indeed; I just picked _a random link_ to show that I tried to look up the problem, and I am not intending to use you as helpdesk.

> > but I have no idea what standard tools are.
> 
> I have no idea what non-standard tools (or more likely a somewhat unusual environment) you have.

I am using an Ubuntu Bionic. However, being a tinker-er myself, I have no idea what "non-standard" tools I might be using (although I did get an epiphany while writing this sentence).

> So let's just try to understand what the `configure` program is doing and what it is trying to tell you.
> [...] 
> You get the idea.

While unnecessary (especially since it seemed to annoy you), I do feel the need to say "Thank you" for going through explaining all of that.

> So now we get to the error and message leading up to that:
> 
> > configure: creating ./config.status
> > configure: error: could not make ./config.status
> 
> After configure has accumulated the information above, it needs to store it somewhere, and that place it has chosen is `./config.status`. When it tries to write out that file, it can't and that is what the "could not make ./config.status" message says.

Something I didn't know / guess 😄 Thank you 

> The most likely causes is that configure does not have write access to "." or that there already is a file called "./config.status" that has permissions set in a way that you can't write to it. For example it could be owned by `root` (from a prior run) and you are now running this as some other non-priviledged user.

It felt unnecessary to mention, but

```console
$ zshdb → λ git master → touch ./config.status
$ zshdb → λ git master → echo $?
0
```

works.

> Since this is more of a "help - what am I doing wrong kind of question" rather than a bug report, I'm closing this.
> 
> If you want helpdesk kind of support, then Stackoverflow is more approprriate. Or consider sponsoring either the project or me.

Unfortunately, stackoverflow does not like my questions - even though it appears that "every question is as good as any" and a lot questions wouldn't need to be asked "if you look hard enough and/or read a lot of manuals". I have posted 2 questions, and now
> [... I'm] in danger of being blocked from asking.

😕

I apologize if the issue was at all disturbing to you. (Although, it may have had to do something with bringing "Apple" into the discussion)

In truth, I am looking forward to put in my pipeline to create deb packages for `bashdb` - and I would prefer if I could fork off of your repo. However, I don't see anything in Github.

I would appreciate it if you'd spend a couple of minutes of either pointing me to the right direction or upload a clone here.

-----

And indeed, if I had looked hard enough, I would've found it: I am using ugrep (https://github.com/Genivia/ugrep/), which claims to be an "in-place replacement" to grep. Removing it from path indeed helped.

While it makes the issue more perplexing (nothing grep-related seems to warn, no mention of "what" failed on the high-level task `configure: creating ./config.status`), _indeed it is none of your fault and concern_.

Cheers!

**Comment by rocky** [comment] 2020-06-22 09:26
I am glad I was able to give you enough insight for you solve your problem somehow. It is not at all clear though that what you think solved the problem is what actually did, but that's okay; it is of no concern. 

And I definitely know that what you report does not contradict what the error message says or anything that what I wrote. (That you might not understand *how* it doesn't again is of no concern and not worth going into.)

If you are in danger of being banned from StackOverflow, then it is more likely the problem is you and not StackOverflow. And then you should problably consider paying people to help you in your interests or tinkereings.  When you do that, the issue of whether you are taking up someone else's time for something that is initially for interest and benefit to you alone is of no concern. 

I realize and suspect may that you be not thinking of it that way. Or rather that you may feel that perhaps your problem is a more general thing (it is not here), may point up to some way code could be improved and down the line or "in the pipeline" you might contribute something back. (It still okay though to pay for people to help you. I am certain this kind of thing happens via helpdesks too.)

Unless you can point to a list of packages that you have already made that are currently on Debian and Ubuntu, I am sorry to report that I am inclined to believe that helping you in that endeavor isn't going to be worth the effort involved from my side. Of course, I welcome a newer bashdb for the newer Debians and Ubuntu and if you happen to get that done, please let me know!

However older versions of  `bashdb` are in older Debians and were last seen in xenial. And somehow that all got done even though this was on sourceforge and without _any_ involvement from me. Furthermore, when I have need to use this from a newer Debian or Ubuntu, I can probably package it myself privately as I have in the past. 

I wish you of the best luck in your tinkerings. I suggest issue trackers, at least the for the projects I wrote and manage, are for bugs and not helpdesk items (until such time as there is a mechanism where you can easily pay for such kind of support via this mechanism). Consider yourself warned.

A long while ago Richard Stallman wrote advice for How to Report a Bug  which you can probably find by googling for.  I suggest you read that and follow that more closely  and fully.
